on:
  release:
    types: [published]

jobs:
  homebrew:
    runs-on: ubuntu-latest
    steps:
      - uses: mislav/bump-homebrew-formula-action@v2
        if: "!contains(github.ref, '-')"
        with:
          formula-name: enver
          formula-path: Formula/enver.rb
          homebrew-tap: lyndonoc/homebrew-tap
          base-branch: main
          download-url: https://github.com/lyndonoc/enver/releases/download/${{ github.ref_name }}/enver-${{ github.ref_name }}-universal-apple-darwin.tar.gz
          commit-message: |
            {{formulaName}} {{version}}
            
            Created by https://github.com/mislav/bump-homebrew-formula-action
        env:
          COMMITTER_TOKEN: ${{ secrets.RELEASE_SECRET }}
